services:
  # 1. PostgreSQL (For Users and Orders)
  postgres_db:
    image: postgres:15-alpine
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB (For the Flexible Product Catalog)
  mongo_db:
    image: mongo:6.0
    container_name: nexus_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis (for fast caching and shopping cart operations)
  redis_cache:
    image: redis:7-alpine
    container_name: nexus_redis
    restart: always
    ports:
      - "6379:6379"

  # 4. Backend API (brain of the system)
  backend_api:
    build: ./backend
    container_name: nexus_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  
    depends_on:
      - postgres_db
      - mongo_db
      - redis_cache    

    environment:
      # DATABASE URL Variables: ------------------
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_db:27017
      # AWS --------------
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}  

volumes:
  postgres_data:
  mongo_data:
