events {
    worker_connections 1024;
}

http {
    # We define a group for traffic going to the backend.
    upstream backend_servers {
        server nexus_backend:8000;
    }

    server {
        listen 80; # Nginx will listen to the world on port 80

       
# Redirect all incoming requests (/) to the backend server (FastAPI).
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}